"""Spotify Support Agent Package."""

from src.spotify_agent.intent_classifier import (
    Classification,
    classify_message,
    classify_conversation,
    SUBSTANTIVE_INTENTS,
    NON_INTENT_CLASSES,
    TECHNICAL_SCOPES,
    INTENT_PRIORITY,
)
from src.spotify_agent.conversation_parser import (
    ParsedMessage,
    ParsedConversation,
    normalize_text,
    parse_message,
    parse_conversation,
    extract_inbound_query,
)

from src.spotify_agent.routing_engine import (
    RoutingDecision,
    route_classification,
    route_message,
    route_conversation,
    QUEUE_SECURITY_ACCOUNT_RECOVERY,
    QUEUE_BILLING_SUPPORT,
    QUEUE_TECHNICAL_TROUBLESHOOTING,
    QUEUE_PLAN_MANAGEMENT,
    QUEUE_REGIONAL_LICENSING,
    QUEUE_CATALOG_CONTENT,
    QUEUE_CATALOG_METADATA,
    QUEUE_PRODUCT_FEEDBACK,
    QUEUE_ARTIST_RIGHTS,
    QUEUE_SENIOR_SUPPORT_ESCALATION,
    QUEUE_PRIVATE_CHANNEL_HANDOFF,
    QUEUE_CLARIFICATION,
    QUEUE_SOCIAL_NON_SUPPORT,
    QUEUE_ACKNOWLEDGMENT_CLOSE,
)

from src.spotify_agent.response_generator import (
    AgentResponse,
    Response,
    generate_response,
)
from src.spotify_agent.agent import (
    AgentResult,
    SpotifySupportAgent,
)
from src.spotify_agent.llm_judge import (
    DEFAULT_GROQ_MODEL,
    DEFAULT_OPENROUTER_MODEL,
    RUBRIC_DIMENSIONS,
    JudgeScore,
    evaluate_response,
    parse_judge_response,
    resolve_judge_config,
    validate_judge_score_dict,
)

__all__ = [
    "Classification",
    "classify_message",
    "classify_conversation",
    "SUBSTANTIVE_INTENTS",
    "NON_INTENT_CLASSES",
    "TECHNICAL_SCOPES",
    "INTENT_PRIORITY",
    "ParsedMessage",
    "ParsedConversation",
    "normalize_text",
    "parse_message",
    "parse_conversation",
    "extract_inbound_query",
    "RoutingDecision",
    "route_classification",
    "route_message",
    "route_conversation",
    "QUEUE_SECURITY_ACCOUNT_RECOVERY",
    "QUEUE_BILLING_SUPPORT",
    "QUEUE_TECHNICAL_TROUBLESHOOTING",
    "QUEUE_PLAN_MANAGEMENT",
    "QUEUE_REGIONAL_LICENSING",
    "QUEUE_CATALOG_CONTENT",
    "QUEUE_CATALOG_METADATA",
    "QUEUE_PRODUCT_FEEDBACK",
    "QUEUE_ARTIST_RIGHTS",
    "QUEUE_SENIOR_SUPPORT_ESCALATION",
    "QUEUE_PRIVATE_CHANNEL_HANDOFF",
    "QUEUE_CLARIFICATION",
    "QUEUE_SOCIAL_NON_SUPPORT",
    "QUEUE_ACKNOWLEDGMENT_CLOSE",
    "AgentResponse",
    "Response",
    "generate_response",
    "AgentResult",
    "SpotifySupportAgent",
    "DEFAULT_OPENROUTER_MODEL",
    "DEFAULT_GROQ_MODEL",
    "RUBRIC_DIMENSIONS",
    "JudgeScore",
    "evaluate_response",
    "parse_judge_response",
    "resolve_judge_config",
    "validate_judge_score_dict",
]
