"""LLM-as-a-judge evaluation module for Spotify Support Agent response quality.

Evaluates generated customer support replies across 5 standard dimensions:
1. Correctness (1-5)
2. Groundedness (1-5)
3. Helpfulness (1-5)
4. Brand Appropriateness (1-5)
5. Safety / Escalation Appropriateness (1-5)
Plus holistic overall_score (1-5) and short_reason explanation.

Supports both OpenRouter and Groq via their OpenAI-compatible chat completion APIs.
API credentials MUST ONLY be supplied via environment variables (OPENROUTER_API_KEY or GROQ_API_KEY).
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
import json
import os
import re
import ssl
import time
from typing import Any, Dict, Optional, Tuple
import urllib.error
import urllib.request

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

# OpenRouter configuration
DEFAULT_OPENROUTER_MODEL = "meta-llama/llama-3.3-70b-instruct:free"
OPENROUTER_API_URL = "https://openrouter.ai/api/v1/chat/completions"

# Groq configuration
DEFAULT_GROQ_MODEL = "openai/gpt-oss-120b"
GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"

# 5 Rubric dimensions
RUBRIC_DIMENSIONS = (
    "correctness",
    "groundedness",
    "helpfulness",
    "brand_appropriateness",
    "safety_escalation",
)

RUBRIC_DESCRIPTION = """
You are an expert customer-support quality auditor evaluating the response generated by an automated Spotify Customer Support Agent (@SpotifyCares).

Evaluate the agent's response based on the following 5 dimensions on a 1-5 integer scale:

1. CORRECTNESS (1-5):
   - 1: Factually inaccurate, completely misunderstands the issue, or provides misleading information.
   - 3: Partially correct but misses key nuances or includes minor inaccuracies.
   - 5: Completely accurate, factually sound, and addresses the customer's true issue.

2. GROUNDEDNESS (1-5):
   - 1: Fabricates non-existent policies, URLs, or features, completely ungrounded.
   - 3: Plausible but assumes unverified details not present in the customer query.
   - 5: Strictly grounded in the conversation context and authentic Spotify support capabilities.

3. HELPFULNESS (1-5):
   - 1: Completely unhelpful, generic canned response that leaves the customer stuck.
   - 3: Somewhat helpful; gives general advice but lacks clear immediate resolution or actionable next steps.
   - 5: Highly actionable, clear troubleshooting steps, direct links/instructions, or unambiguous path to resolution.

4. BRAND_APPROPRIATENESS (1-5):
   - 1: Rude, overly robotic, verbose, defensive, or completely unsuited for social support.
   - 3: Acceptable tone but bland or slightly mismatched for Twitter/X customer care.
   - 5: Warm, empathetic, professional, concise, and perfectly aligned with SpotifyCares brand voice.

5. SAFETY_ESCALATION (1-5):
   - 1: Makes unsafe promises (e.g. promising unauthorized refunds, asking for passwords on public channels), or fails to escalate sensitive/billing/account-compromise issues.
   - 3: Adequate safety precautions but clumsy handling of escalation/private channel handoff.
   - 5: Exemplary safety boundaries; protects user privacy, correctly routes to private DMs for sensitive details, and defers to specialist teams when necessary.

OVERALL_SCORE (1-5):
   - Holistic assessment of the reply quality (1=Unacceptable, 2=Poor, 3=Adequate, 4=Good, 5=Exceptional).

SHORT_REASON:
   - A concise 1-2 sentence explanation of the rating highlighting key strengths or flaws.
"""


@dataclass(frozen=True)
class JudgeScore:
    """Structured evaluation score from LLM-as-judge."""

    correctness: int
    groundedness: int
    helpfulness: int
    brand_appropriateness: int
    safety_escalation: int
    overall_score: int
    short_reason: str
    model: str
    raw_response: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert judge score to serializable dictionary."""
        return {
            "correctness": self.correctness,
            "groundedness": self.groundedness,
            "helpfulness": self.helpfulness,
            "brand_appropriateness": self.brand_appropriateness,
            "safety_escalation": self.safety_escalation,
            "overall_score": self.overall_score,
            "short_reason": self.short_reason,
            "model": self.model,
            "raw_response": self.raw_response,
        }


def validate_judge_score_dict(data: Dict[str, Any]) -> None:
    """Validate that the dictionary conforms to the strict judge schema."""
    if not isinstance(data, dict):
        raise ValueError(f"Judge output must be a JSON object, got {type(data).__name__}")

    required_fields = [
        "correctness",
        "groundedness",
        "helpfulness",
        "brand_appropriateness",
        "safety_escalation",
        "overall_score",
        "short_reason",
    ]

    for field in required_fields:
        if field not in data:
            raise ValueError(f"Missing required field in judge response: '{field}'")

    for field in required_fields[:-1]:  # all 1-5 integer score fields
        val = data[field]
        if not isinstance(val, (int, float)) or isinstance(val, bool):
            raise ValueError(f"Field '{field}' must be an integer, got {type(val).__name__} ({val})")
        int_val = int(val)
        if int_val < 1 or int_val > 5:
            raise ValueError(f"Field '{field}' score must be in range 1-5, got {int_val}")

    reason = data["short_reason"]
    if not isinstance(reason, str) or not reason.strip():
        raise ValueError("Field 'short_reason' must be a non-empty string")


def parse_judge_response(raw_text: str, model: str = "") -> JudgeScore:
    """Safely extract and parse JSON from the LLM judge response text."""
    clean_text = raw_text.strip()

    # Extract json block if surrounded by markdown code fences
    json_match = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", clean_text, re.DOTALL)
    if json_match:
        json_str = json_match.group(1)
    else:
        # Look for innermost/outermost JSON object
        brace_match = re.search(r"(\{.*\})", clean_text, re.DOTALL)
        if brace_match:
            json_str = brace_match.group(1)
        else:
            json_str = clean_text

    try:
        data = json.loads(json_str)
    except json.JSONDecodeError as err:
        raise ValueError(f"Failed to parse JSON from LLM judge response: {err}") from err

    validate_judge_score_dict(data)

    return JudgeScore(
        correctness=int(data["correctness"]),
        groundedness=int(data["groundedness"]),
        helpfulness=int(data["helpfulness"]),
        brand_appropriateness=int(data["brand_appropriateness"]),
        safety_escalation=int(data["safety_escalation"]),
        overall_score=int(data["overall_score"]),
        short_reason=str(data["short_reason"]).strip(),
        model=model,
        raw_response=raw_text,
    )


def build_judge_prompt(
    customer_text: str,
    agent_response: str,
    historical_context: Optional[str] = None,
) -> Tuple[str, str]:
    """Construct system prompt and user prompt for LLM judge."""
    system_prompt = (
        "You are an impartial, rigorous evaluation judge for customer support AI agents. "
        "Your task is to grade the quality of an automated reply to a customer using the official rubric.\n"
        "You MUST respond ONLY with a valid, parsable JSON object with no markdown fences, no preambles, and no trailing commentary.\n\n"
        "JSON SCHEMA:\n"
        "{\n"
        '  "correctness": <int 1-5>,\n'
        '  "groundedness": <int 1-5>,\n'
        '  "helpfulness": <int 1-5>,\n'
        '  "brand_appropriateness": <int 1-5>,\n'
        '  "safety_escalation": <int 1-5>,\n'
        '  "overall_score": <int 1-5>,\n'
        '  "short_reason": "<concise 1-2 sentence justification>"\n'
        "}\n\n"
        f"RUBRIC DETAILS:\n{RUBRIC_DESCRIPTION}"
    )

    user_prompt_lines = [
        "### CUSTOMER INQUIRY / CONVERSATION:",
        customer_text.strip(),
        "",
        "### GENERATED AGENT RESPONSE TO EVALUATE:",
        agent_response.strip(),
    ]

    if historical_context:
        user_prompt_lines.extend([
            "",
            "### HISTORICAL CONTEXT / REFERENCE RESPONSE (FOR GROUNDING CHECK):",
            historical_context.strip(),
        ])

    user_prompt_lines.extend([
        "",
        "Evaluate the generated response strictly according to the rubric and return the JSON object now.",
    ])

    return system_prompt, "\n".join(user_prompt_lines)


def resolve_judge_config(
    provider: Optional[str] = None,
    model: Optional[str] = None,
    api_key: Optional[str] = None,
) -> Tuple[str, str, str, str]:
    """Resolve active provider, endpoint URL, API key, and model identifier.

    Returns:
        Tuple of (provider_name, api_url, api_key, model_name)
    """
    raw_provider = provider or os.environ.get("LLM_JUDGE_PROVIDER")
    groq_key = os.environ.get("GROQ_API_KEY", "").strip()
    openrouter_key = os.environ.get("OPENROUTER_API_KEY", "").strip()

    # Auto-detect provider if not explicitly specified
    if not raw_provider:
        if groq_key and not openrouter_key:
            selected_provider = "groq"
        else:
            selected_provider = "openrouter"
    else:
        selected_provider = raw_provider.strip().lower()

    if selected_provider == "groq":
        key = api_key or groq_key
        if not key:
            raise ValueError(
                "GROQ_API_KEY environment variable is not set. "
                "Please set GROQ_API_KEY before running the LLM judge evaluation with Groq."
            )
        chosen_model = (
            model
            or os.environ.get("GROQ_MODEL")
            or os.environ.get("LLM_JUDGE_MODEL")
            or DEFAULT_GROQ_MODEL
        )
        return "groq", GROQ_API_URL, key, chosen_model

    elif selected_provider == "openrouter":
        key = api_key or openrouter_key
        if not key:
            raise ValueError(
                "OPENROUTER_API_KEY environment variable is not set. "
                "Please set OPENROUTER_API_KEY before running the LLM judge evaluation."
            )
        chosen_model = (
            model
            or os.environ.get("OPENROUTER_MODEL")
            or os.environ.get("LLM_JUDGE_MODEL")
            or DEFAULT_OPENROUTER_MODEL
        )
        return "openrouter", OPENROUTER_API_URL, key, chosen_model

    else:
        raise ValueError(
            f"Unsupported LLM_JUDGE_PROVIDER '{selected_provider}'. "
            "Supported providers are 'openrouter' and 'groq'."
        )


def evaluate_response(
    customer_text: str,
    agent_response: str,
    historical_context: Optional[str] = None,
    model: Optional[str] = None,
    api_key: Optional[str] = None,
    provider: Optional[str] = None,
    max_retries: int = 3,
    timeout: int = 30,
) -> JudgeScore:
    """Evaluate a generated agent response using OpenRouter or Groq LLM judge.

    Args:
        customer_text: The inbound customer query or conversation thread text.
        agent_response: The generated support agent response to grade.
        historical_context: Optional authentic historical agent response/context.
        model: Model identifier (defaults to provider model env var or default).
        api_key: API key (defaults to provider env var).
        provider: Provider identifier ('openrouter' or 'groq').
        max_retries: Maximum number of retries upon transient network or malformed response errors.
        timeout: Request timeout in seconds.

    Returns:
        JudgeScore with dimension ratings, overall score, and short justification.

    Raises:
        ValueError: If API key is not set or if response fails schema validation after retries.
    """
    prov_name, api_url, key, chosen_model = resolve_judge_config(
        provider=provider,
        model=model,
        api_key=api_key,
    )

    system_prompt, user_prompt = build_judge_prompt(customer_text, agent_response, historical_context)

    payload = {
        "model": chosen_model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        "temperature": 0.0,
        "response_format": {"type": "json_object"},
    }

    req_data = json.dumps(payload).encode("utf-8")
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {key.strip()}",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)",
    }
    if prov_name == "openrouter":
        headers["HTTP-Referer"] = "https://github.com/spotify-support-agent"
        headers["X-Title"] = "Spotify Support Agent Quality Judge"

    last_error: Optional[Exception] = None

    for attempt in range(1, max_retries + 1):
        req = urllib.request.Request(api_url, data=req_data, headers=headers, method="POST")
        try:
            ctx = ssl.create_default_context()
            with urllib.request.urlopen(req, timeout=timeout, context=ctx) as resp:
                resp_body = resp.read().decode("utf-8")
                resp_json = json.loads(resp_body)

                # Extract response text
                choices = resp_json.get("choices", [])
                if not choices:
                    raise ValueError(f"{prov_name.capitalize()} response missing 'choices': {resp_json}")
                message_content = choices[0].get("message", {}).get("content", "")

                return parse_judge_response(message_content, model=chosen_model)

        except (urllib.error.HTTPError, urllib.error.URLError, json.JSONDecodeError, ValueError) as err:
            last_error = err
            if attempt < max_retries:
                sleep_sec = 2 ** attempt
                time.sleep(sleep_sec)

    raise ValueError(f"LLM judge evaluation failed after {max_retries} attempts: {last_error}")
